const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('aegis', {
  getState: () => ipcRenderer.invoke('aegis:get-state'),
  pinCurrentChat: () => ipcRenderer.invoke('aegis:pin-current-chat'),
  pinChat: (input) => ipcRenderer.invoke('aegis:pin-chat', input),
  activateChat: (chatId) => ipcRenderer.invoke('aegis:activate-chat', chatId),
  openChat: (chatId) => ipcRenderer.invoke('aegis:open-chat', chatId),
  removeChat: (chatId) => ipcRenderer.invoke('aegis:remove-chat', chatId),
  addMessage: (input) => ipcRenderer.invoke('aegis:add-message', input),
  addContinue: () => ipcRenderer.invoke('aegis:add-continue'),
  sendNext: () => ipcRenderer.invoke('aegis:send-next'),
  toggleAutoDispatch: () => ipcRenderer.invoke('aegis:toggle-auto-dispatch'),
  removeMessage: (itemId) => ipcRenderer.invoke('aegis:remove-message', itemId),
  moveMessage: (itemId, direction) => ipcRenderer.invoke('aegis:move-message', itemId, direction),
  clearHistory: () => ipcRenderer.invoke('aegis:clear-history'),
  importDocument: () => ipcRenderer.invoke('aegis:import-document'),
  extractPrompts: (documentId) => ipcRenderer.invoke('aegis:extract-prompts', documentId),
  queuePrompt: (documentId, promptId) => ipcRenderer.invoke('aegis:queue-prompt', documentId, promptId),
  queuePack: (documentId) => ipcRenderer.invoke('aegis:queue-pack', documentId),
  runSupervisor: (input) => ipcRenderer.invoke('aegis:run-supervisor', input),
  toggleAutopilot: (chatId) => ipcRenderer.invoke('aegis:toggle-autopilot', chatId),
  startAllAutopilots: () => ipcRenderer.invoke('aegis:start-all-autopilots'),
  stopAllAutopilots: () => ipcRenderer.invoke('aegis:stop-all-autopilots'),
  checkAllAutopilots: () => ipcRenderer.invoke('aegis:check-all-autopilots'),
  approveDecision: (decisionId) => ipcRenderer.invoke('aegis:approve-decision', decisionId),
  discardDecision: (decisionId) => ipcRenderer.invoke('aegis:discard-decision', decisionId),
  updateProject: (input) => ipcRenderer.invoke('aegis:update-project', input),
  updateSettings: (input) => ipcRenderer.invoke('aegis:update-settings', input),
  reloadChatGPT: () => ipcRenderer.invoke('aegis:reload-chatgpt'),
  chatGPTHome: () => ipcRenderer.invoke('aegis:chatgpt-home'),
  openExternalChatGPT: () => ipcRenderer.invoke('aegis:open-external-chatgpt'),
  copyDiagnostics: () => ipcRenderer.invoke('aegis:copy-diagnostics'),
  openLogs: () => ipcRenderer.invoke('aegis:open-logs'),
  setPanelWidth: (width) => ipcRenderer.invoke('aegis:set-panel-width', width),
  setChatPanel: (input) => ipcRenderer.invoke('aegis:set-chat-panel', input),
  onState: (callback) => ipcRenderer.on('aegis:state', (_event, nextState) => callback(nextState)),
  onLayout: (callback) => ipcRenderer.on('aegis:layout', (_event, layout) => callback(layout))
});
