const $=s=>document.querySelector(s);let state=null;
function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2500)}
async function call(fn,...args){try{const r=await window.aegis[fn](...args);if(r&&!r.ok)toast(r.error||'Ошибка');return r}catch(e){toast(e.message)}}
function esc(s){return String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function render(s){state=s;const b=s.browser||{},sup=s.supervisor||{},u=sup.usageToday||{},settings=s.settings||{};
 $('#chat-status').textContent=b.signedIn?(b.detail||'ChatGPT готов'):'Войди в ChatGPT справа';$('#api-dot').style.color=b.composerReady?'#28a745':'#d58b24';
 const spent=Number(u.estimatedPaidUsd||0),limit=Number(settings.maxGeminiSpendUsdPerDay||0),calls=Number(u.calls||0),callLimit=Number(settings.maxGeminiCallsPerDay||0);
 $('#spent').textContent=`$${spent.toFixed(3)} / ${limit?`$${limit.toFixed(2)}`:'∞'}`;$('#calls').textContent=`${calls} / ${callLimit||'∞'}`;$('#budget-progress').value=limit?Math.min(100,spent/limit*100):0;
 const chats=(s.chats||[]).slice(0,3);$('#chats').innerHTML=chats.length?chats.map(c=>`<div class="chat ${c.id===s.activeChatId?'active':''}"><div class="chat-head"><input type="checkbox" data-toggle="${c.id}" ${c.autopilotEnabled?'checked':''}><div class="chat-title">${esc(c.title)}</div></div><div class="chat-state">${esc(c.autopilotState||'off')}${c.autopilotPauseReason?` · ${esc(c.autopilotPauseReason)}`:''}</div><div class="chat-actions"><button data-open="${c.id}">Открыть</button><button data-remove="${c.id}">Убрать</button></div></div>`).join(''):'<div>Закрепи до трёх чатов кнопкой «+ текущий чат».</div>';
 $('#summary').innerHTML=`<div>Активно: <b>${sup.autopilotChatCount||0}</b></div><div>Проверок в очереди: <b>${sup.schedulerQueueCount||0}</b></div><div>Scheduler: <b>${sup.schedulerBusy?'работает':'ожидает'}</b></div><div>Ошибок сегодня: <b>${(s.events||[]).filter(e=>e.tone==='danger').length}</b></div>`;
}
$('#start').onclick=()=>call('startAllAutopilots');$('#stop').onclick=()=>call('stopAllAutopilots');$('#check').onclick=()=>call('checkAllAutopilots');$('#pin').onclick=()=>call('pinCurrentChat');$('#logs').onclick=()=>call('openLogs');$('#copy').onclick=async()=>{await call('copyDiagnostics');toast('Диагностика скопирована')};
$('#chats').onclick=e=>{const t=e.target;if(t.dataset.open)call('openChat',t.dataset.open);if(t.dataset.remove)call('removeChat',t.dataset.remove)};$('#chats').onchange=e=>{if(e.target.dataset.toggle)call('toggleAutopilot',e.target.dataset.toggle)};
$('#settings').onclick=()=>{const s=state.settings||{};$('#model').value=s.geminiModel||'gemini-2.5-flash';$('#money').value=s.maxGeminiSpendUsdPerDay??0.5;$('#daily').value=s.maxGeminiCallsPerDay??250;$('#cooldown').value=s.supervisorCooldownSec??30;$('#key').value='';$('#settings-dialog').showModal()};
$('#save').onclick=async e=>{e.preventDefault();const r=await call('updateSettings',{geminiKey:$('#key').value,geminiModel:$('#model').value,maxGeminiSpendUsdPerDay:Number($('#money').value),maxGeminiCallsPerDay:Number($('#daily').value),supervisorCooldownSec:Number($('#cooldown').value),supervisorEnabled:true,supervisorMode:'auto',chatSkin:'off'});if(r?.ok)$('#settings-dialog').close()};
window.aegis.onState(render);window.aegis.getState().then(render);window.aegis.setChatPanel({visible:true});
